pipeline {
  agent none
  stages {
    stage('Back-end') {
      agent {
        docker {
          image 'maven:3.9.16-eclipse-temurin-11'
          alwaysPull true
          reuseNode true
        }
      }
      steps {
        sh 'mvn --version'
      }
    }
    stage('Front-end') {
      agent {
        docker {
          image 'node:26-alpine'
          alwaysPull true
          reuseNode true
        }
      }
      steps {
        sh 'node --version'
      }
    }
  }
}
